### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by seymar** [onetune/spotify-web-helper#16]
I get the following warnings when I listen to the `status-will-change` event and close Spotify.app

```
(node:53272) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 27): TypeError: "string" must be a string, Buffer, or ArrayBuffer
(node:53423) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:53423) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): TypeError: Cannot read property 'length' of undefined
```

Am I missing something or does this module need an update?

Node version: v7.2.1

P.S.: This module is awesome 😄

**Comment by JonnyBurger** [comment]
Thanks! I made a fix for this. Update to 1.7 to receive it.
In such an occasion, an 'error' event is being fired. See the README.md for details.

Cheers
Jonny
