### ISSUE TITLE
Event For When a User Seeks

### ISSUE THREAD

**Issue by itotallyrock** [onetune/spotify-web-helper#17]
It would be useful for the API to emit an event when the user seeks or the song's position changes faster than time has passed.  The main feature I personally would use this for would be a custom progress bars.  At the moment I would have to constantly check the position of the song to ensure it's position.  While I could simply set off a simple CSS animation and only change it if the user seeks.

It doesn't seem too complicated of a feature either.  A simple check during the status check to see if the length of time passed is the same as that of the song's time played.

**Comment by JonnyBurger** [comment]
Great idea.

PR would be welcome!

**Comment by itotallyrock** [comment]
closed with #28 being merged
