### ISSUE TITLE
"No user logged in" when getting CSRF token

### ISSUE THREAD

**Issue by nickdima** [onetune/spotify-web-helper#2]
I have Spotify opened, I'm logged in but when `getCsrfToken` gets called it responds with "No user logged in"

**Comment by nickdima** [comment]
I'll close this since I think it's out of your project's control. It worked after restarting Spotify.

**Comment by JonnyBurger** [comment]
Thanks for the report nonetheless. I have tried it myself but couldn't reproduce the bug. I can also confirm that the module does not throw the error itself, it comes from Spotify.
