### ISSUE TITLE
Connection loss

### ISSUE THREAD

**Issue by Exotrom** [onetune/spotify-web-helper#22]
Hi, sometimes I get a connection loss after a few minutes. This exception appears:

```
{ Error: getaddrinfo ENOENT zczykmwpwe.spotilocal.com:4370
    at Object.exports._errnoException (util.js:1022:11)
    at errnoException (dns.js:33:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'getaddrinfo',
  hostname: 'zczykmwpwe.spotilocal.com',
  host: 'zczykmwpwe.spotilocal.com',
  port: '4370' }
```

I tried several computers (all WIN10) but sometimes it seems that my dns cannot resolve the spotilocal hostname.

Of course this might be an issue of my dns server and can be fixed by editing the host file but I think there is no need for a *.spotilocal.com hostname. I tried using the 127.0.0.1 IP instead of the spotilocal domain and it seems to work like a charm.

Maybe you can try the following code or something similar:
```
function generateRandomLocalHostName() {
	// Generate a random hostname under the .spotilocal.com domain
	return '127.0.0.1'; //generateRandomString(10) + '.spotilocal.com';
}
```

**Comment by JonnyBurger** [comment]
Seems to work on macOS also!

Thanks! 👍
