### ISSUE TITLE
Switch from Request

### ISSUE THREAD

**Issue by itotallyrock** [onetune/spotify-web-helper#24]
Request is a very bulky library for the simple requests necessary for the app.  It adds a lot of overhead and load time to my package because request takes 200ms to initialize from nothing.  Rather than try to resolve the issue with the request package, the easiest solution is to change to [http.request](https://nodejs.org/api/http.html#http_http_request_options_callback) or perhaps the native [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) if we feel like being progressive about it.

**Comment by JonnyBurger** [comment]
I would accept a PR.
I can also recommend [got](https://github.com/sindresorhus/got) as a lighter alternative to `request`.
