### ISSUE TITLE
Takes 60 sec or more to connect

### ISSUE THREAD

**Issue by bobbylaporte** [onetune/spotify-web-helper#34]
I've upgraded to the latest version recently, and it's taking between 1 and 2 minutes to get the first `status-will-change` event. This is happening on both Windows and Mac. Anyone else experiencing this or have a workaround?

**Comment by sekwah41** [comment]
It seems to take a long time to even execute the player ready. That is probably why.

**Comment by sekwah41** [comment]
Found its because it takes ages slowly checking each individual possible port... Ill take a look at recoding it to either check multiple requests at once or to set a timeout value.

**Comment by sekwah41** [comment]
If you are still looking for a fix for this, i have made a pull request which works for me at least pretty fast but I have not fully tested it #35

**Comment by JonnyBurger** [comment]
Fixed by #35, thanks again!
