### ISSUE TITLE
SpotifyWebHelper cpu usage at over 90%

### ISSUE THREAD

**Issue by anker2000** [onetune/spotify-web-helper#38]
I've noticed the SpotifyWebHelper process launched by spotify-web-helper frequently goes rogue and hits 90% cpu usage. I'm on a mac. Not sure this is caused by spotify-web-helper. Is anyone else experiencing this?

**Comment by williamd** [comment]
I can chime in and confirm, also on a Mac running 10.3.3. One core seems to be maxed out until I quit the process.

**Comment by itotallyrock** [comment]
I don't have a Mac to test this out on; however, the spotifywebhelper process is not controlled by this package.  We simply start it if it isn't running.  I'm closing this issue as it is likely you are experiencing [this issue](https://community.spotify.com/t5/Desktop-Mac/High-CPU-usage-on-OSX/td-p/1140129).

**Comment by agreatthing** [comment]
A quick followup, I tried the solutions provided in the link. Unfortunately they did not help the problem. A quick guess is that the process may be started regardless if Spotify itself is open. There might be a check there to be made.
